import HomeIcon from "@material-ui/icons/Home";
import ShortTextIcon from "@material-ui/icons/ShortText";
import SubscriptionsIcon from "@material-ui/icons/Subscriptions";
import VideoLibraryIcon from "@material-ui/icons/VideoLibrary";
import HistoryIcon from "@material-ui/icons/History";
import PersonalVideoIcon from "@material-ui/icons/PersonalVideo";
import ThumbUpIcon from "@material-ui/icons/ThumbUp";
import WatchLaterIcon from "@material-ui/icons/WatchLater";
// import ary_news from "../../assets/sidebar_menu/ary-news.png";
// import city_41 from "../../assets/sidebar_menu/city_41.jfif";
// import tech_gun from "../../assets/sidebar_menu/tech_gun.jpg";
// import geeky_shows from "../../assets/sidebar_menu/geeky_shows.jpg";

const array = [
  { logo: <HomeIcon />, text: "Home" },
  { logo: <ShortTextIcon />, text: "shorts" },
  { logo: <SubscriptionsIcon />, text: "Subscriptions" },
  { logo: <VideoLibraryIcon />, text: "Library" },
  { logo: <HistoryIcon />, text: "History" },
  { logo: <PersonalVideoIcon />, text: "Your videos" },
  { logo: <ThumbUpIcon />, text: "Liked videos" },
  { logo: <WatchLaterIcon />, text: "Watch Later" },
  { logo: <HomeIcon />, text: "Home" },
  { logo: <ShortTextIcon />, text: "shorts" },
  { logo: <SubscriptionsIcon />, text: "Subscriptions" },
  { logo: <VideoLibraryIcon />, text: "Library" },
  { logo: <HistoryIcon />, text: "History" },
  { logo: <PersonalVideoIcon />, text: "Your videos" },
  { logo: <ThumbUpIcon />, text: "Liked videos" },
  { logo: <WatchLaterIcon />, text: "Watch Later" },
  { logo: <HomeIcon />, text: "Home" },
  { logo: <ShortTextIcon />, text: "shorts" },
  { logo: <SubscriptionsIcon />, text: "Subscriptions" },
  { logo: <VideoLibraryIcon />, text: "Library" },
  { logo: <HistoryIcon />, text: "History" },
  { logo: <PersonalVideoIcon />, text: "Your videos" },
  { logo: <ThumbUpIcon />, text: "Liked videos" },
  { logo: <WatchLaterIcon />, text: "Watch Later" },
  { logo: <HomeIcon />, text: "Home" },
  { logo: <ShortTextIcon />, text: "shorts" },
  { logo: <SubscriptionsIcon />, text: "Subscriptions" },
  { logo: <VideoLibraryIcon />, text: "Library" },
  { logo: <HistoryIcon />, text: "History" },
  { logo: <PersonalVideoIcon />, text: "Your videos" },
  { logo: <ThumbUpIcon />, text: "Liked videos" },
  { logo: <WatchLaterIcon />, text: "Watch Later" },
  { logo: <HomeIcon />, text: "Home" },
  { logo: <ShortTextIcon />, text: "shorts" },
  { logo: <SubscriptionsIcon />, text: "Subscriptions" },
  { logo: <VideoLibraryIcon />, text: "Library" },
  { logo: <HistoryIcon />, text: "History" },
  { logo: <PersonalVideoIcon />, text: "Your videos" },
  { logo: <ThumbUpIcon />, text: "Liked videos" },
  { logo: <WatchLaterIcon />, text: "Watch Later" },
  { logo: <HomeIcon />, text: "Home" },
  { logo: <ShortTextIcon />, text: "shorts" },
  { logo: <SubscriptionsIcon />, text: "Subscriptions" },
  { logo: <VideoLibraryIcon />, text: "Library" },
  { logo: <HistoryIcon />, text: "History" },
  { logo: <PersonalVideoIcon />, text: "Your videos" },
  { logo: <ThumbUpIcon />, text: "Liked videos" },
  { logo: <WatchLaterIcon />, text: "Watch Later" },
  { logo: <HomeIcon />, text: "Home" },
  { logo: <ShortTextIcon />, text: "shorts" },
  { logo: <SubscriptionsIcon />, text: "Subscriptions" },
  { logo: <VideoLibraryIcon />, text: "Library" },
  { logo: <HistoryIcon />, text: "History" },
  { logo: <PersonalVideoIcon />, text: "Your videos" },
  { logo: <ThumbUpIcon />, text: "Liked videos" },
  { logo: <WatchLaterIcon />, text: "Watch Later" },
  { logo: <HomeIcon />, text: "Home" },
  { logo: <ShortTextIcon />, text: "shorts" },
  { logo: <SubscriptionsIcon />, text: "Subscriptions" },
  { logo: <VideoLibraryIcon />, text: "Library" },
  { logo: <HistoryIcon />, text: "History" },
  { logo: <PersonalVideoIcon />, text: "Your videos" },
  { logo: <ThumbUpIcon />, text: "Liked videos" },
  { logo: <WatchLaterIcon />, text: "Watch Later" },
  { logo: <HomeIcon />, text: "Home" },
  { logo: <ShortTextIcon />, text: "shorts" },
  { logo: <SubscriptionsIcon />, text: "Subscriptions" },
  { logo: <VideoLibraryIcon />, text: "Library" },
  { logo: <HistoryIcon />, text: "History" },
  { logo: <PersonalVideoIcon />, text: "Your videos" },
  { logo: <ThumbUpIcon />, text: "Liked videos" },
  { logo: <WatchLaterIcon />, text: "Watch Later" },
  { logo: <HomeIcon />, text: "Home" },
  { logo: <ShortTextIcon />, text: "shorts" },
  { logo: <SubscriptionsIcon />, text: "Subscriptions" },
  { logo: <VideoLibraryIcon />, text: "Library" },
  { logo: <HistoryIcon />, text: "History" },
  { logo: <PersonalVideoIcon />, text: "Your videos" },
  { logo: <ThumbUpIcon />, text: "Liked videos" },
  { logo: <WatchLaterIcon />, text: "Watch Later" },
  { logo: <HomeIcon />, text: "Home" },
  { logo: <ShortTextIcon />, text: "shorts" },
  { logo: <SubscriptionsIcon />, text: "Subscriptions" },
  { logo: <VideoLibraryIcon />, text: "Library" },
  { logo: <HistoryIcon />, text: "History" },
  { logo: <PersonalVideoIcon />, text: "Your videos" },
  { logo: <ThumbUpIcon />, text: "Liked videos" },
  { logo: <WatchLaterIcon />, text: "Watch Later" },
  { logo: <HomeIcon />, text: "Home" },
  { logo: <ShortTextIcon />, text: "shorts" },
  { logo: <SubscriptionsIcon />, text: "Subscriptions" },
  { logo: <VideoLibraryIcon />, text: "Library" },
  { logo: <HistoryIcon />, text: "History" },
  { logo: <PersonalVideoIcon />, text: "Your videos" },
  { logo: <ThumbUpIcon />, text: "Liked videos" },
  { logo: <WatchLaterIcon />, text: "Watch Later" },
  { logo: <HomeIcon />, text: "Home" },
  { logo: <ShortTextIcon />, text: "shorts" },
  { logo: <SubscriptionsIcon />, text: "Subscriptions" },
  { logo: <VideoLibraryIcon />, text: "Library" },
  { logo: <HistoryIcon />, text: "History" },
  { logo: <PersonalVideoIcon />, text: "Your videos" },
  { logo: <ThumbUpIcon />, text: "Liked videos" },
  { logo: <WatchLaterIcon />, text: "Watch Later" },
  { logo: <HomeIcon />, text: "Home" },
  { logo: <ShortTextIcon />, text: "shorts" },
  { logo: <SubscriptionsIcon />, text: "Subscriptions" },
  { logo: <VideoLibraryIcon />, text: "Library" },
  { logo: <HistoryIcon />, text: "History" },
  { logo: <PersonalVideoIcon />, text: "Your videos" },
  { logo: <ThumbUpIcon />, text: "Liked videos" },
  { logo: <WatchLaterIcon />, text: "Watch Later" },
  { logo: <HomeIcon />, text: "Home" },
  { logo: <ShortTextIcon />, text: "shorts" },
  { logo: <SubscriptionsIcon />, text: "Subscriptions" },
  { logo: <VideoLibraryIcon />, text: "Library" },
  { logo: <HistoryIcon />, text: "History" },
  { logo: <PersonalVideoIcon />, text: "Your videos" },
  { logo: <ThumbUpIcon />, text: "Liked videos" },
  { logo: <WatchLaterIcon />, text: "Watch Later" },
  // { logo: ary_news, text: "Home" },
  // { logo: city_41, text: "fdsdf" },
  // { logo: tech_gun, text: "Home" },
  // { logo: geeky_shows, text: "shorgtfts" },
];
export default array;
